// GENERATO da data/brand/design-system/tokens.json (colori) — non modificare a mano; le estensioni sono segnalate in docs/DESIGN-SYSTEM-NOTE.md
export const C = {
  "terra": "#3d2b1a",
  "terraTesto": "#2c1d0e",
  "terraMedio": "#6b5040",
  "terraChiaro": "#9a8070",
  "ocra": "#c8862a",
  "ocraChiaro": "#e8a045",
  "sabbia": "#f5f0e8",
  "sabbiaScura": "#e8dfc8",
  "bordo": "#d8c8b0",
  "bianco": "#ffffff",
  "ocraTint": "#fdf0e0",
  "verdePresenza": "#3daa70",
  "verdePresenzaTint": "#eaf7f0",
  "rossoAssenza": "#c0392b",
  "rossoAssenzaTint": "#fdecea",
  "rossoAssenzaMappa": "rgba(210,40,40,0.5)",
  "bluNavigazione": "#2595ff",
  "verdeWhatsapp": "#22c55e",
  "azzurroTelegram": "#2aabee",
  "mappaStrade": "#706f6f",
  "mappaArea": "#ffffff",
  "mappaParcheggi": "#e6d867",
  "mappaAiuole": "#9ec583",
  "mappaPiazzaEventi": "#d38267",
  "mappaPostazioneLibera": "#e8e2d8",
  "mappaPostazioneLiberaBordo": "#c8c0b4",
  "mappaPostazioneFuoriOrario": "#d9c9ad",
  "gialloOccasionale": "#e0a800",
  "gialloOccasionaleTesto": "#a07000",
  "verdePresenzaTesto": "#2e7d52"
};
